routes/admin.php
<?php
use Illuminate\Support\Facades\Route;


Route::get('/admin','AdminController@index')->name('admin');

//-----------articles routes -----------
Route::post('/admin/article', 'ArticleController@store')->name('article.store');
Route::get('/admin/article/create', 'ArticleController@create')->name('article.create');
Route::get('/admin/article/{article_id}', 'ArticleController@delete')->name('article.delete');
Route::get('/admin/article/{article_id}/edit', 'ArticleController@edit')->name('article.edit');
Route::patch('admin/article/article_num={article_id}', 'ArticleController@update')->name('article.update');



Route::resource('tag','TagController',['except' => ['create']]);

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use unisharp\laravelfilemanager\Lfm;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    Lfm::routes();});

Route::get('/home', 'HomeController@index')->name('home');


Route::get('article={article_id}', 'ArticleController@show')->name('article.show');

resources/views/admin.blade.php
@extends('layouts.app')

@section('content')

    <div id="articles_table">
        <div class="row justify-content-center">
            <div class="py-4 col-md-10 ">
                <div class="card">
                    <div class="card-header font-weight-bolder d-flex">
                        <span class="card_header_text pt-2">Articles</span>
                        <a href="{{route('article.create')}}" class="btn btn-dark ml-auto" role="button">add</a>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 mb-2">
                            <div class="my-custom-scrollbar">
                                <table class="table table-bordered table-hover">
                                    <thead class="thead-light ">
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Title</th>
                                        <th scope="col">Description</th>
                                        <th scope="col">Created At</th>
                                        <th scope="col">Updated At</th>

                                        <th scope="col"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach( $Articles as $article)
                                        <tr>
                                            <th scope="row">
                                                {{$loop->iteration}}
                                            </th>
                                            <td>
                                                <a href="{{route('article.show',$article->id)}}">{{$article->title}}</a>
                                            </td>
                                            <td>{{$article->description}}</td>
                                            <td>{{$article->created_at}}</td>
                                            <td>{{$article->updated_at}}</td>

                                            <td class="text-center" data-toggle="collapse"
                                                href="#article{{$loop->iteration}}">
                                                <i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i>
                                            </td>
                                        </tr>
                                        <tr class="hide-table-padding">
                                            <td colspan="4">
                                                <div id="article{{$loop->iteration}}"
                                                     class="collapse in p-3 text-center">
                                                    <a class="btn btn-success"
                                                       href="{{route('article.edit',$article->id)}}">Edit</a>
                                                    <a class="btn btn-danger"
                                                       href="{{route('article.delete',$article->id)}}">Delete</a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr class="solid container">

    <div id="Tags_table">
        <div class="row justify-content-center d-flex">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header font-weight-bolder d-flex">
                        <span class="card_header_text pt-2">Tags</span>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 mb-2">
                            <div class="my-custom-scrollbar">
                                <table class="table table-bordered table-hover">
                                    <thead class="thead-light ">
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">name</th>
                                        <th scope="col">Created At</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach( $Tags as $tag)
                                        <tr data-toggle="collapse" href="#">
                                            <th scope="row">{{$loop->iteration}}</th>
                                            <td>{{$tag->name}}</td>
                                            <td>{{$tag->created_at}}</td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 ">

                <div class="card">
                    <div class="card-header font-weight-bolder">Create New Tag</div>
                    <div class="card-body">
                        <form method="post" action="{{route('tag.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">

                                <label for="name"
                                       class="col-md-12 col-form-label">Name</label>

                                <div class="col-md-12">
                                    <input id="name" type="text"
                                           class="form-control @error('name') is-invalid @enderror" name="name"
                                           value="{{old('name')}}" autocomplete="name">

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="row mt-md-3 justify-content-center">
                                    <div class="col-md-5 p-0">
                                        <button type="submit" class="btn btn-dark btn-block">
                                            {{ __('Add New Tag') }}
                                        </button>
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>



@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container text-center">
        <div class="row mx-auto my-auto">
            <div id="recipeCarousel" class="carousel slide w-100" data-ride="carousel">
                <div class="carousel-inner w-100" role="listbox">
                    <div class="carousel-item active">
                        <div class="col-md-2 ">
                            <div class="carousel-card ">
                                <a href="https://laravel.com/docs">Popular</a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item ">
                        <div class="col-md-2 ">
                            <div class="carousel-card ">
                                <a href="https://laravel.com/docs">MOMENTUM</a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item ">
                        <div class="col-md-2 ">
                            <div class="carousel-card ">
                                <a href="https://laravel.com/docs">ELMENTAL</a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item ">
                        <div class="col-md-2 ">
                            <div class="carousel-card ">
                                <a href="https://laravel.com/docs">ZORA</a>
                            </div>
                        </div>
                    </div>

                    <div class="carousel-item ">
                        <div class="col-md-2 ">
                            <div class="carousel-card ">
                                <a href="https://laravel.com/docs">FORGE</a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item ">
                        <div class="col-md-2 ">
                            <div class="carousel-card ">
                                <a href="https://laravel.com/docs">MARKER</a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item ">
                        <div class="col-md-2 ">
                            <div class="carousel-card ">
                                <a href="https://laravel.com/docs">CORONAVIRUS</a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item ">
                        <div class="col-md-2 ">
                            <div class="carousel-card ">
                                <a href="https://laravel.com/docs">GEN</a>
                            </div>
                        </div>
                    </div>

                    <a class="carousel-control-prev w-auto" href="#recipeCarousel" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon bg-dark rounded-circle"></span>
                    </a>
                    <a class="carousel-control-next w-auto" href="#recipeCarousel" role="button" data-slide="next">
                        <span class="carousel-control-next-icon bg-dark  rounded-circle"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center">
            <div class="card-group py-4">
                <div class="col-sm-12 col-md-4 col-lg-4 p-0">
                    <div class="card border-0">
                        <img src="/images/{{$First[0]->image}}" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title heading">
                                <a href="{{route('article.show',$First[0]->id)}}">{{$First[0]->title}}</a>
                            </h5>
                            <p class="card-text">{{substr($First[0]->description,0,100) . '...'}}</p>
                            <div class="d-flex ">
                            @foreach($First[0]->tags as $tag)
                                <h6 class="mr-2"><span class="badge badge-secondary">{{$tag->name}}</span></h6>
                            @endforeach
                            </div>
                            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                        </div>
                    </div>
                </div>

                <div class="col-sm-12 col-md-4 col-lg-5 p-0">
                    <div class="card border-0">
                        @for($i=1;$i<4;$i++)
                            <div class="col-sm-12 col-md-12 col-lg-12 mb-4">
                                <div class="card border-0">
                                    <div class="row no-gutters">
                                        <div class="col-4">
                                            <img src="/images/{{$First[$i]->image}}" class="img-fluid" alt="">
                                        </div>
                                        <div class="col-8">
                                            <div class="card-block px-2 heading-small">
                                                <a href="{{route('article.show',$First[$i]->id)}}">{{$First[$i]->title}}</a>
                                            </div>
                                            <p class="card-text px-2">{{substr($First[4]->description,0,40) . '...'}}</p>
                                            <div class="d-flex ml-2 ">
                                                @foreach($First[$i]->tags as $tag)
                                                    <h6 class="mr-2"><span class="badge badge-secondary">{{$tag->name}}</span></h6>
                                                @endforeach
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        @endfor
                    </div>
                </div>
                <div class="col-sm-12 col-md-4 col-lg-3 p-0">
                    <div class="card border-0">
                        <img src="/images/{{$First[4]->image}}" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title heading-medium">
                                <a href="{{route('article.show',$First[4]->id)}}">{{$First[4]->title}}</a>
                            </h5>
                            <p class="card-text ">{{substr($First[4]->description,0,100) . '...'}}</p>
                            <div class="d-flex ">
                                @foreach($First[4]->tags as $tag)
                                    <h6 class="mr-2"><span class="badge badge-secondary">{{$tag->name}}</span></h6>
                                @endforeach
                            </div>
                            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="container text-center ">
        <div class="row ">
            <div class="col-lg-10">
                <hr class="solid">
            </div>
        </div>
    </div>
    <div class="container  d-flex">
        <div class="col-lg-8">
            @foreach( $Articles as $article)
                <div class="card my-lg-5 border-0">
                    <div class="row no-gutters">
                        <div class="col-8">
                            <div class="px-2">
                                <div class="card-subheading">
                                    Based on your interests
                                </div>
                                <div class="heading">
                                    <a href="{{route('article.show',$article->id)}}">{{$article->title}}</a>
                                </div>
                                <div class="card-subheading-small">
                                    {{substr($article->description,0,100) . '...'}}
                                </div>
                                <div class="d-flex">
                                @foreach($article->tags as $tag)
                                    <h6 class="mr-2"><span class="badge badge-secondary">{{$tag->name}}</span></h6>
                                @endforeach
                                </div>
                                <div class="article-info mt-4">
                                    <div class="article-info-left">
                                        <div class="">
                                            <a class="profile-avatar">
                                                <img
                                                    src="https://media-exp1.licdn.com/dms/image/C5603AQGaNl8fjmgRww/profile-displayphoto-shrink_400_400/0?e=1599696000&v=beta&t=wweDVpBWOHoKpBtoVSkmIPJWY8zoOvQNfNeWc4JeaRU"
                                                    class="avatar-image" alt="">
                                            </a>
                                        </div>
                                        <div class="article-info-center">
                                            <div class="username">Nazeeh Saifi</div>
                                            <div><span
                                                    class="date">{{$article->created_at->shortEnglishMonth }} {{$article->created_at->day }}  </span>
                                                <span>.</span>
                                                <span class="read-time"> {{$loop->iteration}} min read</span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="article-info-right">
                                        <i class="fa fa-bookmark-o bookmark-link fa-2x" aria-hidden="true"></i>
                                        <i class="fa fa-ellipsis-h more-options-link fa-2x"
                                           aria-hidden="true"></i>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <img src="/images/{{$article->image}}" width="100%" height="100%" alt="">
                        </div>
                    </div>
                </div>
            @endforeach
        </div>

        <div class="col-lg-4">
            @foreach( $Articles as $article)
                <div class="card my-lg-4 border-0">
                    <div class="row no-gutters">
                        <div class="col">
                            <div class="px-4">
                                <div class="heading-medium">
                                    {{$article->title}}
                                </div>
                                <div class="article-info ">
                                    <div class="article-info-left">
                                        <div>
                                            <a class="profile-avatar">
                                                <img
                                                    src="https://media-exp1.licdn.com/dms/image/C5603AQGaNl8fjmgRww/profile-displayphoto-shrink_400_400/0?e=1599696000&v=beta&t=wweDVpBWOHoKpBtoVSkmIPJWY8zoOvQNfNeWc4JeaRU"
                                                    class="avatar-image" alt="">
                                            </a>
                                        </div>
                                        <div class="article-info-center">
                                            <div class="username">Nazeeh Saifi</div>
                                            <div><span class="date">{{$article->created_at}}</span><span
                                                    class="read-time"> 4 min read</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            @endforeach
        </div>
    </div>


    <div class="card-body">
        @if (session('status'))
            <div class="alert alert-success" role="alert">
                {{ session('status') }}
            </div>
        @endif
    </div>


@endsection

@push('script')
<script>

    $('#recipeCarousel').carousel({
        interval: 10000
    });

    $('.carousel .carousel-item').each(function(){
        var minPerSlide = 20;
        var next = $(this).next();
        if (!next.length) {
            next = $(this).siblings(':first');
        }
        next.children(':first-child').clone().appendTo($(this));

        for (var i=0;i<minPerSlide;i++) {
            next=next.next();
            if (!next.length) {
                next = $(this).siblings(':first');
            }

            next.children(':first-child').clone().appendTo($(this));
        }
    });
</script>
@endpush